// Slackwater — GPL v3. Validated CHS current gates (chs-current-gates.json,
// generated by tools/gen-chs-gates.mjs from the station-corrections registry):
// the Inside Passage passes whose FITTED slack timing passed the M47 validation
// bar against CHS's own published events (spikes/chs-currents-fit/README.md —
// slack median ≤15 min / worst ≤30 min, extrema median ≤20 min, peak speed
// median ≤0.5 kn, no reversed axis). Gates that failed are not bundled at all:
// absent, not broken-looking.
//
// Identity only is bundled. The harmonic model is fitted on-device from IWLS
// wcsp1/wcdp1 (210 days — Rayleigh: K1/P1, which drive PNW diurnal inequality,
// separate only at ≥183 d; 60 d measurably fails the bar) and the flood/ebb
// axis arrives from IWLS station metadata at fit time. Nothing CHS-published
// ships in the app — same licensing posture as the tide ports (chs-online §2).
import Foundation

/// Bundled identity for one validated CHS current gate.
struct ChsCurrentGateInfo: Decodable, Identifiable, Hashable {
    let id: String        // registry key, e.g. "chs-dodd-narrows"
    let name: String
    let region: String
    let aliases: [String]
    let latitude: Double
    let longitude: Double
    let timezone: String
    /// Registry pairing: a bundled CHS tide port whose water renders as the
    /// second track above the gate's current strip. Absent = current-only.
    let tideReference: String?

    var tz: TimeZone { TimeZone(identifier: timezone) ?? .current }

    static let all: [ChsCurrentGateInfo] = {
        guard let url = Bundle.main.url(forResource: "chs-current-gates", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let gates = try? JSONDecoder().decode([ChsCurrentGateInfo].self, from: data) else { return [] }
        return gates.sorted { $0.name < $1.name }
    }()

    /// Same ranking as TideStationRecord.searchRank (mirrors web search.ts).
    func searchRank(_ query: String) -> Int? {
        if name.lowercased().contains(query) { return 0 }
        if region.lowercased().contains(query) { return 1 }
        if aliases.contains(where: { $0.contains(query) }) { return 2 }
        return nil
    }
}

/// A current harmonic model fitted on this device from IWLS `wcsp1`/`wcdp1`
/// predictions — CHS-derived, and it never leaves the device. The flood/ebb
/// axis is CHS station metadata, stored here for the same reason the
/// constituents are: fetched by this user, kept local, never re-served.
struct ChsCurrentModel: Codable {
    struct Con: Codable { let name: String; let amplitude: Double; let phase: Double }
    var schemaVersion = 1
    let stationID: String     // registry key
    let iwlsID: String        // resolved at runtime by position (never bundled)
    let iwlsName: String
    let fittedAt: Date
    let fitStartMs: Double
    let fitEndMs: Double
    let floodDirection: Double
    let ebbDirection: Double
    /// Z0: net mean flow along the flood axis, knots, signed.
    let offset: Double
    /// Fit residual, knots.
    let rms: Double
    let constituents: [Con]
}

extension ChsModelStore {
    /// Gate models live beside the port models, suffixed so the two Codable
    /// shapes never read each other's files.
    static func currentUrl(_ stationID: String) -> URL {
        dir.appendingPathComponent("\(stationID)-current.json")
    }

    static func loadCurrent(_ stationID: String) -> ChsCurrentModel? {
        guard let data = try? Data(contentsOf: currentUrl(stationID)) else { return nil }
        return try? JSONDecoder().decode(ChsCurrentModel.self, from: data)
    }

    static func saveCurrent(_ model: ChsCurrentModel) throws {
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try JSONEncoder().encode(model).write(to: currentUrl(model.stationID), options: .atomic)
    }
}

extension ChsCurrentGateInfo {
    /// A fitted CHS gate renders through the exact same record/engine/view path
    /// as a bundled NOAA current station — provenance shows only in the footer.
    func record(with model: ChsCurrentModel) -> CurrentStationRecord {
        CurrentStationRecord(
            id: id, name: name, region: region, aliases: aliases,
            latitude: latitude, longitude: longitude, timezone: timezone,
            floodDirection: model.floodDirection, ebbDirection: model.ebbDirection,
            meanFlow: model.offset, tideReference: tideReference,
            constituents: model.constituents.map {
                CurrentStationRecord.Con(name: $0.name, amplitude: $0.amplitude, phase: $0.phase)
            })
    }
}

extension CurrentStationRecord {
    /// Fitted-on-device CHS gate, vs a bundled NOAA harmonic station.
    var isChs: Bool { id.hasPrefix("chs-") }
}
