// Slackwater — GPL v3. Validated CHS current gates (chs-current-gates.json,
// generated by tools/gen-chs-gates.mjs from the station-corrections registry):
// the Inside Passage passes whose FITTED slack timing passed the M47 validation
// bar against CHS's own published events (spikes/chs-currents-fit/README.md —
// slack median ≤15 min / worst ≤30 min, extrema median ≤20 min, peak speed
// median ≤0.5 kn, no reversed axis). Gates that failed are not bundled at all:
// absent, not broken-looking.
//
// Identity only is bundled. The harmonic model is fitted on-device from IWLS
// wcsp1/wcdp1 (210 days — Rayleigh: K1/P1, which drive PNW diurnal inequality,
// separate only at ≥183 d; 60 d measurably fails the bar) and the flood/ebb
// axis arrives from IWLS station metadata at fit time. Nothing CHS-published
// ships in the app — same licensing posture as the tide ports (chs-online §2).
import Foundation
import TideEngine

/// Bundled identity for one validated CHS current gate.
struct ChsCurrentGateInfo: Decodable, Identifiable, Hashable {
    let id: String        // registry key, e.g. "chs-dodd-narrows"
    let name: String
    let region: String
    let aliases: [String]
    let latitude: Double
    let longitude: Double
    let timezone: String
    /// Registry pairing: a bundled CHS tide port whose water renders as the
    /// second track above the gate's current strip. Absent = current-only.
    let tideReference: String?
    /// The window whose fit is FINAL for THIS gate — 60 or 210 d, from the M51
    /// per-gate validation, not a blanket number.
    let fitDays: Double
    /// The honest worst-case slack error, minutes, of the 60-day fast answer.
    /// Absent means no fast answer is offered: either the gate is final at 60 d
    /// anyway, or its 60-day error is over the usefulness floor.
    let provisionalSlackMinutes: Int?
    /// True for the 7 fit-rejects: findable identities backed by official CHS
    /// predictions fetched on demand, never fitted on-device (online-gates
    /// spec §1). Absent/false for the 11 shipped, fittable gates.
    var online: Bool? = nil
    /// Plain-words measured error for the honesty card — this gate's own
    /// number, never a generic hedge. Present only when `online`.
    var onlineNote: String? = nil

    /// A fit-reject backed by official CHS predictions fetched on demand —
    /// never fitted, never queued (online-gates spec §1). Bundled entries
    /// without the key decode as offline (the 11 shipped gates).
    var isOnline: Bool { online ?? false }

    var tz: TimeZone { TimeZone(identifier: timezone) ?? .current }

    /// The trailing 60 days — every gate's first fit, and a prefix of the
    /// 210-day fetch, so a provisional answer costs no extra request.
    static let provisionalDays = 60.0

    /// Does this gate get a fast answer before its full model? Only when the
    /// full window is longer than the provisional one AND the measured 60-day
    /// error cleared the floor (both encoded in the bundle by gen-chs-gates).
    var offersProvisional: Bool { fitDays > Self.provisionalDays && provisionalSlackMinutes != nil }

    /// Rough wall-clock for the refinement leg — the chunks between 60 d and
    /// the full window, two series each, at the fetcher's 2.5 s pacing. Feeds
    /// "stay connected about N more minutes"; coarse by design.
    var refineSeconds: Double { ((fitDays - Self.provisionalDays) / 7).rounded(.up) * 2 * 2.5 }

    static let all: [ChsCurrentGateInfo] = {
        guard let url = Bundle.main.url(forResource: "chs-current-gates", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let gates = try? JSONDecoder().decode([ChsCurrentGateInfo].self, from: data) else { return [] }
        return gates.sorted { $0.name < $1.name }
    }()

    /// Same ranking as TideStationRecord.searchRank (mirrors web search.ts).
    func searchRank(_ query: String) -> Int? {
        if name.lowercased().contains(query) { return 0 }
        if region.lowercased().contains(query) { return 1 }
        if aliases.contains(where: { $0.contains(query) }) { return 2 }
        return nil
    }
}

/// A current harmonic model fitted on this device from IWLS `wcsp1`/`wcdp1`
/// predictions — CHS-derived, and it never leaves the device. The flood/ebb
/// axis is CHS station metadata, stored here for the same reason the
/// constituents are: fetched by this user, kept local, never re-served.
struct ChsCurrentModel: Codable {
    struct Con: Codable { let name: String; let amplitude: Double; let phase: Double }
    var schemaVersion = 1
    let stationID: String     // registry key
    let iwlsID: String        // resolved at runtime by position (never bundled)
    let iwlsName: String
    let fittedAt: Date
    let fitStartMs: Double
    let fitEndMs: Double
    /// Days of data behind this fit. Less than the gate's `fitDays` means this
    /// is the PROVISIONAL fast answer, not the final model. Optional so a model
    /// stored by build ≤14 (always the full window) still decodes.
    let fitDays: Double?
    let floodDirection: Double
    let ebbDirection: Double
    /// Z0: net mean flow along the flood axis, knots, signed.
    let offset: Double
    /// Fit residual, knots.
    let rms: Double
    let constituents: [Con]
}

extension ChsModelStore {
    /// Gate models live beside the port models, suffixed so the two Codable
    /// shapes never read each other's files.
    static func currentUrl(_ stationID: String) -> URL {
        dir.appendingPathComponent("\(stationID)-current.json")
    }

    static func loadCurrent(_ stationID: String) -> ChsCurrentModel? {
        guard let data = try? Data(contentsOf: currentUrl(stationID)) else { return nil }
        return try? JSONDecoder().decode(ChsCurrentModel.self, from: data)
    }

    static func saveCurrent(_ model: ChsCurrentModel) throws {
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try JSONEncoder().encode(model).write(to: currentUrl(model.stationID), options: .atomic)
    }

    /// The online gate's fetched window lives beside the fitted models, under
    /// its own suffix — same reason `-current.json` doesn't shadow `.json`.
    static func onlineUrl(_ stationID: String) -> URL {
        dir.appendingPathComponent("\(stationID)-online.json")
    }

    static func loadOnline(_ stationID: String) -> ChsOnlineWindow? {
        guard let data = try? Data(contentsOf: onlineUrl(stationID)) else { return nil }
        return try? JSONDecoder().decode(ChsOnlineWindow.self, from: data)
    }

    static func saveOnline(_ window: ChsOnlineWindow) throws {
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try JSONEncoder().encode(window).write(to: onlineUrl(window.stationID), options: .atomic)
    }
}

// MARK: - The fetched window (online gates: official CHS predictions, no fit)

/// A window of official CHS current predictions for one online (fit-reject)
/// gate — fetched on demand, never fitted, kept local like the fitted models.
/// The strip span (`start`/`end`) is `Timeline`'s ‑48h…+132h around today's
/// local midnight AT FETCH TIME, so a stale window is a coverage question,
/// not a staleness heuristic — see `coversStrip`.
struct ChsOnlineWindow: Codable {
    var schemaVersion = 1
    let stationID: String
    let iwlsName: String
    /// The gate's own timezone (added beyond the brief's shape): `coversStrip`
    /// has to rebuild "today's local midnight" the same way `TimelineData`
    /// does, and a window has to carry that alongside its dates to do it
    /// without reaching back into the bundled gate identity.
    let timezone: String
    let fetchedAt: Date
    let start: Date            // today −48h at fetch, the Timeline window
    let end: Date              // today +132h at fetch
    let floodDirection: Double // IWLS metadata at fetch time, kept local
    let ebbDirection: Double
    let times: [Double]        // epoch seconds, 15-min official samples
    let speeds: [Double]       // signed kn along the flood axis (project())

    var points: [CurrentPoint] {
        zip(times, speeds).map { CurrentPoint(time: Date(timeIntervalSince1970: $0), speed: $1) }
    }

    /// Does the stored window still cover the FULL strip `Timeline` would
    /// build right now? True iff it reaches at least `now`'s local
    /// −48h…+132h — the exact rule Task 5 refetches against.
    func coversStrip(now: Date) -> Bool {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = TimeZone(identifier: timezone) ?? .current
        let today = cal.startOfDay(for: now)
        let neededStart = today.addingTimeInterval(-Timeline.backHours * 3600)
        let neededEnd = today.addingTimeInterval(Timeline.forwardHours * 3600)
        return start <= neededStart && end >= neededEnd
    }

    /// The list/search card's reading: nearest 15-min sample to `now` (a card
    /// tolerates the ≤7.5 min slop; `OnlineGateDetailView`'s scrub is where
    /// interpolating the drawn curve earns its keep), and the next event from
    /// the same fetched series `sampleEvents` scans — the same shape
    /// `CurrentStationRecord.cardState(at:)` returns for a fitted gate, so the
    /// card rendering doesn't need to know which kind of gate it's reading.
    func cardState(at now: Date) -> CurrentCardState {
        let signed = points.min { abs($0.time.timeIntervalSince(now)) < abs($1.time.timeIntervalSince(now)) }?.speed ?? 0
        let next = sampleEvents(points).first { $0.time > now }
        return CurrentCardState(signed: signed, next: next)
    }
}

// MARK: - The fast answer, in words

/// The copy for a provisional gate lives here, in one place, because it has to
/// say the same thing on the card, in the detail and in the manager — and
/// because the number in it is THIS gate's measured 60-day slack error, never a
/// generic hedge. Register: what it is, how wrong it can be, what to do.
extension ChsCurrentGateInfo {
    /// "±35 min" — the badge-sized version.
    var provisionalTolerance: String { "±\(provisionalSlackMinutes ?? 0) min" }

    var provisionalHeadline: String {
        "Fitted from the last \(Int(Self.provisionalDays)) days — slack at \(name) can be off by up to ~\(provisionalSlackMinutes ?? 0) min."
    }

    var provisionalExpectation: String {
        "Stay connected for \(durationPhrase(refineSeconds)) more and Slackwater refines it to the full \(Int(fitDays))-day model, in place — nothing to tap."
    }

    /// Is this stored model the fast answer rather than the full model?
    func isProvisional(_ model: ChsCurrentModel) -> Bool { (model.fitDays ?? fitDays) < fitDays }

    /// A fitted CHS gate renders through the exact same record/engine/view path
    /// as a bundled NOAA current station — provenance shows only in the footer.
    func record(with model: ChsCurrentModel) -> CurrentStationRecord {
        CurrentStationRecord(
            id: id, name: name, region: region, aliases: aliases,
            latitude: latitude, longitude: longitude, timezone: timezone,
            floodDirection: model.floodDirection, ebbDirection: model.ebbDirection,
            meanFlow: model.offset, tideReference: tideReference,
            constituents: model.constituents.map {
                CurrentStationRecord.Con(name: $0.name, amplitude: $0.amplitude, phase: $0.phase)
            })
    }
}

extension CurrentStationRecord {
    /// Fitted-on-device CHS gate, vs a bundled NOAA harmonic station.
    var isChs: Bool { id.hasPrefix("chs-") }
    /// This record's `StationItem` id — what the favorite star and the
    /// Recents record must write for the list to resolve it. NOAA current
    /// stations are namespaced "current:<id>" (Friday Harbor has both a tide
    /// and a current station); a CHS gate keys the catalog bare. Hand-building
    /// the prefixed form at a call site minted favorites no section could
    /// resolve (fresh-install bug, 2026-08-08).
    var itemId: String { isChs ? id : "current:" + id }
    /// The bundled gate identity behind a fitted CHS record — where the
    /// per-gate window and the fast answer's tolerance live.
    var chsGate: ChsCurrentGateInfo? { ChsCurrentGateInfo.all.first { $0.id == id } }
}
