// Slackwater — GPL v3. Validated CHS current gates (chs-current-gates.json,
// generated by tools/gen-chs-gates.mjs from the station-corrections registry):
// the Inside Passage passes whose FITTED slack timing passed the M47 validation
// bar against CHS's own published events (spikes/chs-currents-fit/README.md —
// slack median ≤15 min / worst ≤30 min, extrema median ≤20 min, peak speed
// median ≤0.5 kn, no reversed axis). Gates that failed are not bundled at all:
// absent, not broken-looking.
//
// Identity only is bundled. The harmonic model is fitted on-device from IWLS
// wcsp1/wcdp1 (210 days — Rayleigh: K1/P1, which drive PNW diurnal inequality,
// separate only at ≥183 d; 60 d measurably fails the bar) and the flood/ebb
// axis arrives from IWLS station metadata at fit time. Nothing CHS-published
// ships in the app — same licensing posture as the tide ports (chs-online §2).
import Foundation
import TideEngine

/// Bundled identity for one validated CHS current gate.
struct ChsCurrentGateInfo: Decodable, Identifiable, Hashable, StationIdentity {
    let id: String        // registry key, e.g. "chs-dodd-narrows"
    let name: String
    let region: String
    let aliases: [String]
    let latitude: Double
    let longitude: Double
    let timezone: String
    /// Registry pairing: a bundled CHS tide port whose water renders as the
    /// second track above the gate's current strip. Absent = current-only.
    let tideReference: String?
    /// The window whose fit is FINAL for THIS gate — 60 or 210 d, from the M51
    /// per-gate validation, not a blanket number.
    let fitDays: Double
    /// The honest worst-case slack error, minutes, of the 60-day fast answer.
    /// Absent means no fast answer is offered: either the gate is final at 60 d
    /// anyway, or its 60-day error is over the usefulness floor.
    let provisionalSlackMinutes: Int?
    /// True for the 7 fit-rejects: findable identities backed by official CHS
    /// predictions fetched on demand, never fitted on-device (online-gates
    /// spec §1). Absent/false for the 11 shipped, fittable gates.
    var online: Bool? = nil
    /// Plain-words measured error for the honesty card — this gate's own
    /// number, never a generic hedge. Present only when `online`.
    var onlineNote: String? = nil

    /// A fit-reject backed by official CHS predictions fetched on demand —
    /// never fitted, never queued (online-gates spec §1). Bundled entries
    /// without the key decode as offline (the 11 shipped gates).
    var isOnline: Bool { online ?? false }

    var tz: TimeZone { TimeZone(identifier: timezone) ?? .current }

    /// The trailing 60 days — every gate's first fit, and a prefix of the
    /// 210-day fetch, so a provisional answer costs no extra request.
    static let provisionalDays = 60.0

    /// Does this gate get a fast answer before its full model? Only when the
    /// full window is longer than the provisional one AND the measured 60-day
    /// error cleared the floor (both encoded in the bundle by gen-chs-gates).
    var offersProvisional: Bool { fitDays > Self.provisionalDays && provisionalSlackMinutes != nil }

    /// Rough wall-clock for the refinement leg — the chunks between 60 d and
    /// the full window, two series each, at the fetcher's 2.5 s pacing. Feeds
    /// "stay connected about N more minutes"; coarse by design.
    var refineSeconds: Double { ((fitDays - Self.provisionalDays) / 7).rounded(.up) * 2 * 2.5 }

    static let all: [ChsCurrentGateInfo] = bundled("chs-current-gates")
}

/// The gate model's pre-merge name (see ChsModel) — SlackwaterTests still
/// spells it.
typealias ChsCurrentModel = ChsModel

extension ChsModelStore {
    /// Gate models live beside the port models, suffixed so a gate model never
    /// shadows a port model of the same key.
    static func currentUrl(_ stationID: String) -> URL { url(stationID, suffix: "-current") }
    static func loadCurrent(_ stationID: String) -> ChsModel? { load(stationID, suffix: "-current") }
    static func saveCurrent(_ model: ChsModel) throws { try save(model, id: model.stationID, suffix: "-current") }

    /// The online gate's fetched window lives beside the fitted models, under
    /// its own suffix — same reason `-current.json` doesn't shadow `.json`.
    static func onlineUrl(_ stationID: String) -> URL { url(stationID, suffix: "-online") }
    static func loadOnline(_ stationID: String) -> ChsOnlineWindow? { load(stationID, suffix: "-online") }

    /// Merges into whatever is already on disk rather than replacing it.
    /// Replacing would make a prefetch destructive: fetching the next block
    /// would discard the current one, and paging back would refetch what the
    /// user just had.
    ///
    /// The prune cut is the start of TODAY's strip — `Timeline.window`'s own
    /// answer, never re-derived here, for the reason its doc comment gives —
    /// or the incoming window's own start, whichever is earlier. The cut never
    /// discards data the incoming window itself covers: a fetch anchored in the
    /// past (the picker is unbounded in both directions, spec §5) starts before
    /// today's strip does, and a fixed `today − 48h` cut would delete the block
    /// that fetch just paid for, fail `covers` for that anchor, and refetch it
    /// on every visit forever.
    ///
    /// Returns what it WROTE — the union — never the block handed in. The one
    /// caller that keeps the result (`fetchOnlineWindow`, and through it
    /// `OnlineGateDetailView`) would otherwise hold a window narrower than the
    /// disk's and answer `covers` false for a week the app already has, sending
    /// the very next page-back to the network for data it just saved.
    ///
    // ponytail: no forward cap. A 30-day block is ~2880 samples (~90KB JSON);
    // someone who pages a year out accumulates ~1MB on a gate they evidently
    // care about, and -chsResetModels already clears it. Add a cap when a real
    // file gets big.
    @discardableResult
    static func saveOnline(_ window: ChsOnlineWindow) throws -> ChsOnlineWindow {
        let today = todayLocal(TimeZone(identifier: window.timezone) ?? .current)
        let cut = min(Timeline.window(anchor: today).start, window.start)
        let merged = loadOnline(window.stationID)?.merging(window, prunedBefore: cut) ?? window
        try save(merged, id: window.stationID, suffix: "-online")
        return merged
    }
}

/// Where the next speculative fetch starts: the local midnight at the stored
/// window's far edge. Blocks land on `chunkPlan`'s absolute 7-day grid, so the
/// overlap this creates costs nothing and the seam can never leave a gap.
func prefetchAnchor(after window: ChsOnlineWindow, tz: TimeZone) -> Date {
    var cal = Calendar(identifier: .gregorian)
    cal.timeZone = tz
    return cal.startOfDay(for: window.end)
}

// MARK: - The fetched window (online gates: official CHS predictions, no fit)

/// A window of official CHS current predictions for one online (fit-reject)
/// gate — fetched on demand, never fitted, kept local like the fitted models.
/// `start`/`end` is the span the samples actually cover — 30 days forward of
/// the fetch's anchor, `Timeline.window`'s back-pad behind it — and it grows
/// as later fetches merge in (`merging`). So a stale window is a coverage
/// question, not a staleness heuristic — see `covers`.
struct ChsOnlineWindow: Codable {
    var schemaVersion = 1
    let stationID: String
    let iwlsName: String
    /// The gate's own timezone (added beyond the brief's shape), carried
    /// alongside the window's dates without reaching back into the bundled
    /// gate identity.
    let timezone: String
    let fetchedAt: Date
    let start: Date            // Timeline.window(anchor:).start at fetch, pruned forward
    let end: Date              // anchor + Timeline.onlineFetchDays, clamped to the samples
    let floodDirection: Double // IWLS metadata at fetch time, kept local
    let ebbDirection: Double
    let times: [Double]        // epoch seconds, 15-min official samples
    let speeds: [Double]       // signed kn along the flood axis (project())

    var points: [CurrentPoint] {
        zip(times, speeds).map { CurrentPoint(time: Date(timeIntervalSince1970: $0), speed: $1) }
    }

    /// Does the stored window cover the FULL strip `Timeline` would build for
    /// `anchor`? The window is computed by `Timeline.window`, never re-derived
    /// here — a second derivation drifts, and the failure mode is this
    /// returning true for a window with a hole in it, which renders as a
    /// strip with a dead zone.
    func covers(anchor: Date) -> Bool {
        let need = Timeline.window(anchor: anchor)
        return start <= need.start && end >= need.end
    }

    /// IWLS's last returned sample routinely lands one 15-min interval short of
    /// the requested end, and `fetchOnlineWindow` clamps `end` down to it — so
    /// two blocks that ought to abut can arrive one sample apart. `merging`
    /// tolerates exactly that much at the seam and no more: a wider gap means a
    /// sample is genuinely missing, which is a hole, and a hole must stay
    /// disjoint rather than be papered over.
    static let sampleInterval = 900.0

    /// Union `other`'s samples into this window by timestamp and widen the
    /// bounds, dropping everything before `prunedBefore`.
    ///
    /// Union, not append: the fetch chunks land on an absolute 7-day grid, so
    /// a refetch routinely overlaps what is already stored, and appending
    /// would hand `sampleEvents` a series with every overlapped sample twice.
    ///
    /// `start` follows the prune. If it did not, `covers` would keep claiming
    /// a range whose samples had just been deleted.
    func merging(_ other: ChsOnlineWindow, prunedBefore: Date) -> ChsOnlineWindow {
        // Two blocks separated by more than a sample have no samples between
        // them, and a window spanning both would answer `covers` true for an
        // anchor in the gap — the same lie as an unpruned `start`, from the
        // other end. The newer block wins outright, prune and all: it is a
        // fresh fetch, whose own start is never earlier than the cut.
        let slack = Self.sampleInterval
        guard start <= other.end.addingTimeInterval(slack),
              other.start <= end.addingTimeInterval(slack) else { return other }
        let cut = prunedBefore.timeIntervalSince1970
        var byTime = Dictionary(zip(times, speeds), uniquingKeysWith: { _, b in b })
        for (t, v) in zip(other.times, other.speeds) { byTime[t] = v }
        let kept = byTime.filter { $0.key >= cut }.sorted { $0.key < $1.key }
        return ChsOnlineWindow(
            stationID: stationID, iwlsName: other.iwlsName, timezone: timezone,
            fetchedAt: other.fetchedAt,
            start: max(min(start, other.start), prunedBefore),
            end: max(end, other.end),
            floodDirection: other.floodDirection, ebbDirection: other.ebbDirection,
            times: kept.map(\.key), speeds: kept.map(\.value))
    }

    /// This window with everything before `cut` dropped — nil when nothing
    /// survives. `start` follows the cut for `merging`'s reason: an unpruned
    /// start keeps `covers` claiming a range whose samples are gone.
    func pruned(before cut: Date) -> ChsOnlineWindow? {
        guard start < cut else { return self }
        guard end > cut else { return nil }
        let c = cut.timeIntervalSince1970
        let kept = zip(times, speeds).filter { $0.0 >= c }
        return ChsOnlineWindow(stationID: stationID, iwlsName: iwlsName, timezone: timezone,
                               fetchedAt: fetchedAt, start: cut, end: end,
                               floodDirection: floodDirection, ebbDirection: ebbDirection,
                               times: kept.map { $0.0 }, speeds: kept.map { $0.1 })
    }

    /// The list/search card's reading: nearest 15-min sample to `now` (a card
    /// tolerates the ≤7.5 min slop; `OnlineGateDetailView`'s scrub is where
    /// interpolating the drawn curve earns its keep), and the next event from
    /// the same fetched series `sampleEvents` scans — the same shape
    /// `CurrentStationRecord.cardState(at:)` returns for a fitted gate, so the
    /// card rendering doesn't need to know which kind of gate it's reading.
    func cardState(at now: Date) -> CurrentCardState {
        let signed = points.min { abs($0.time.timeIntervalSince(now)) < abs($1.time.timeIntervalSince(now)) }?.speed ?? 0
        let next = sampleEvents(points).first { $0.time > now }
        return CurrentCardState(signed: signed, next: next)
    }
}

/// The on-disk shape for an online gate (#67 item 4): DISJOINT fetched
/// blocks, sorted by start. The single start/end window before it made every
/// disjoint merge lossy — a far-forward pick discarded today's block, and
/// paging back refetched ~30 days the app had just held. Blocks stay pairwise
/// separated by more than `sampleInterval`; anything closer merges on save.
/// Coverage questions go to a SINGLE block: the gap between blocks has no
/// samples, and claiming it renders a strip with a dead zone.
struct ChsOnlineStore: Codable {
    var schemaVersion = 2
    let stationID: String
    let blocks: [ChsOnlineWindow]

    /// The one block covering `anchor`'s whole strip, or nil — never a stitch
    /// across a gap.
    func block(covering anchor: Date) -> ChsOnlineWindow? {
        blocks.first { $0.covers(anchor: anchor) }
    }

    /// The block whose span contains `window`'s — what `saveOnline` returns:
    /// the caller's copy must never be narrower than the disk's.
    func block(spanning window: ChsOnlineWindow) -> ChsOnlineWindow? {
        blocks.first { $0.start <= window.start && $0.end >= window.end }
    }

    /// Union `window` in: absorb every stored block that overlaps or abuts it
    /// (within `sampleInterval` slack — the seam a clamped fetch end
    /// produces), keep the rest, prune everything to `cut`, drop empties.
    /// One ascending pass absorbs a chain: stored blocks are pairwise
    /// disjoint, so only the incoming block can bridge two of them, and
    /// sorted order means it meets each neighbour after absorbing the last.
    /// `merging`'s own disjoint guard never fires here — the test above is
    /// the same test it applies.
    func inserting(_ window: ChsOnlineWindow, prunedBefore cut: Date) -> ChsOnlineStore {
        let slack = ChsOnlineWindow.sampleInterval
        var merged = window
        var rest: [ChsOnlineWindow] = []
        for b in blocks.sorted(by: { $0.start < $1.start }) {
            if b.start <= merged.end.addingTimeInterval(slack),
               merged.start <= b.end.addingTimeInterval(slack) {
                merged = b.merging(merged, prunedBefore: cut)
            } else if let kept = b.pruned(before: cut) {
                rest.append(kept)
            }
        }
        if let kept = merged.pruned(before: cut) { rest.append(kept) }
        return ChsOnlineStore(stationID: stationID,
                              blocks: rest.sorted { $0.start < $1.start })
    }
}

// MARK: - The fast answer, in words

/// The copy for a provisional gate lives here, in one place, because it has to
/// say the same thing on the card, in the detail and in the manager — and
/// because the number in it is THIS gate's measured 60-day slack error, never a
/// generic hedge. Register: what it is, how wrong it can be, what to do.
extension ChsCurrentGateInfo {
    /// "±35 min" — the badge-sized version.
    var provisionalTolerance: String { "±\(provisionalSlackMinutes ?? 0) min" }

    var provisionalHeadline: String {
        "Fitted from the last \(Int(Self.provisionalDays)) days — slack at \(name) can be off by up to ~\(provisionalSlackMinutes ?? 0) min."
    }

    /// Offline, "stay connected" is advice you can't act on — say what's true
    /// instead, without implying a wait in progress.
    func provisionalExpectation(online: Bool) -> String {
        online
            ? "Stay connected for \(durationPhrase(refineSeconds)) more and Slackwater refines it to the full \(Int(fitDays))-day model, in place — nothing to tap."
            : "The fast answer is already on this device; next time you're connected, Slackwater refines it to the full \(Int(fitDays))-day model — nothing to tap."
    }

    /// Is this stored model the fast answer rather than the full model?
    func isProvisional(_ model: ChsModel) -> Bool { (model.fitDays ?? fitDays) < fitDays }

    /// A fitted CHS gate renders through the exact same record/engine/view path
    /// as a bundled NOAA current station — provenance shows only in the footer.
    func record(with model: ChsModel) -> CurrentStationRecord {
        CurrentStationRecord(
            id: id, name: name, region: region, aliases: aliases,
            latitude: latitude, longitude: longitude, timezone: timezone,
            // A gate fit always stores the axis; nil is the merged model's
            // tide-port side, which never reaches here (the store suffixes).
            floodDirection: model.floodDirection ?? 0, ebbDirection: model.ebbDirection ?? 0,
            meanFlow: model.offset, tideReference: tideReference,
            constituents: model.constituents)
    }
}

extension CurrentStationRecord {
    /// Fitted-on-device CHS gate, vs a bundled NOAA harmonic station.
    var isChs: Bool { id.hasPrefix("chs-") }
    /// This record's `StationItem` id — what the favorite star and the
    /// Recents record must write for the list to resolve it. NOAA current
    /// stations are namespaced "current:<id>" (Friday Harbor has both a tide
    /// and a current station); a CHS gate keys the catalog bare. Hand-building
    /// the prefixed form at a call site minted favorites no section could
    /// resolve (fresh-install bug, 2026-08-08).
    var itemId: String { isChs ? id : "current:" + id }
    /// The bundled gate identity behind a fitted CHS record — where the
    /// per-gate window and the fast answer's tolerance live.
    var chsGate: ChsCurrentGateInfo? { ChsCurrentGateInfo.all.first { $0.id == id } }
}
