// Slackwater — GPL v3. Derived current gates (chs-gates.json, generated by
// tools/gen-chs-gates.mjs from the station-corrections registry): a pass with
// NO current station of its own (Malibu Rapids). Slack is the reference tide
// port's high/low water plus a fixed lag — cruising-community consensus, not a
// CHS current prediction — so slack TIMES and a flood/ebb PHASE are honest,
// but never a speed. Mirrors slackwater-web chsStations.ts (derived) +
// chs/current.ts (deriveCurrentState); the math lives in TideEngine's
// DerivedSlackStation, kept in step with the web.
import Foundation
import TideEngine

/// Bundled identity for one derived gate. `reference` is a bundled CHS tide
/// port (chs-stations.json) whose on-device fitted model supplies the
/// high/low water the gate's slacks derive from — the gate is predictable
/// offline exactly when its reference port is fitted.
struct ChsGateInfo: Decodable, Identifiable, Hashable, StationIdentity {
    let id: String        // registry key, e.g. "chs-malibu-rapids"
    let name: String
    let region: String
    let aliases: [String]
    let latitude: Double
    let longitude: Double
    let timezone: String
    let reference: String // registry key of the bundled reference tide port
    let referenceName: String
    let hwLagMinutes: Double
    let lwLagMinutes: Double
    let magnitudeNote: String?

    var tz: TimeZone { TimeZone(identifier: timezone) ?? .current }

    static let all: [ChsGateInfo] = bundled("chs-gates")
}

/// A derived gate whose reference port has a fitted model — everything the
/// detail needs, navigable like the other records.
struct DerivedGateRecord: Hashable {
    let gate: ChsGateInfo
    let port: TideStationRecord   // the reference port, fitted on this device

    var engineGate: DerivedSlackStation {
        DerivedSlackStation(reference: port.harmonicStation,
                            hwLagMinutes: gate.hwLagMinutes, lwLagMinutes: gate.lwLagMinutes)
    }
}

/// What a derived gate's list card shows: phase now + the next slack. No
/// speed exists to show (web StationCard: a phase pill, never knots).
struct DerivedGateCardState {
    let phase: DerivedPhase
    let nextSlack: DerivedSlackEvent?
}

extension DerivedGateRecord {
    func cardState(at now: Date) -> DerivedGateCardState {
        // ±30h guarantees bracketing slacks exist, like the other cards.
        let slacks = engineGate.slacks(from: now.addingTimeInterval(-30 * 3600),
                                       to: now.addingTimeInterval(30 * 3600))
        return DerivedGateCardState(phase: engineGate.phase(at: now, slacks: slacks),
                                    nextSlack: slacks.first { $0.time > now })
    }
}

extension DerivedPhase {
    /// "Flooding" / "Ebbing" / "Slack" — the phase pill's word.
    var word: String {
        switch self {
        case .flood: "Flooding"
        case .ebb: "Ebbing"
        case .slack: "Slack"
        }
    }

    /// Plain-word companion for non-sailors — same words as
    /// `CurrentPhase.gloss`, see the rationale there (#59).
    var gloss: String? {
        switch self {
        case .flood: "incoming"
        case .ebb: "outgoing"
        case .slack: nil
        }
    }
}
