// Slackwater — GPL v3. The identity half of the two large NOAA catalogs.
import Foundation

/// A NOAA station as the list, the search and the map pins know it: identity
/// and nothing else.
///
/// The full records carry ~110k harmonic constituents between them, and the
/// first frame reads none of them (#317) — so `StationItem.all` is built from
/// `station-index.json` (1.3 MB) instead of stations.json + currents.json
/// (9.1 MB), and a station's model is resolved by id when something actually
/// needs to predict. `TideStationRecord.byId` / `CurrentStationRecord.byId`
/// are that resolution, and each one decodes its catalog on first use.
struct StationIndexInfo: Decodable, Identifiable, Hashable, StationIdentity {
    let id: String
    let name: String
    let region: String
    let aliases: [String]
    let latitude: Double
    let longitude: Double
    let timezone: String

    var tz: TimeZone { TimeZone(identifier: timezone) ?? .current }

    /// The identity of a record already in hand — how a downloaded catalog
    /// generation and the widget's single-record scan reach the same type.
    init(_ s: some StationIdentity, timezone: String) {
        id = s.id
        name = s.name
        region = s.region
        aliases = s.aliases
        latitude = s.latitude
        longitude = s.longitude
        self.timezone = timezone
    }
}

extension StationIndexInfo {
    init(_ record: TideStationRecord) { self.init(record, timezone: record.timezone) }
    init(_ record: CurrentStationRecord) { self.init(record, timezone: record.timezone) }

    /// The full tide record behind this identity, decoding stations.json on
    /// first use. Nil is unreachable for a bundled station — the index is
    /// generated from the catalog — so callers may treat it as "not renderable".
    var tideRecord: TideStationRecord? { TideStationRecord.byId[id] }
    var currentRecord: CurrentStationRecord? { CurrentStationRecord.byId[id] }
}

/// The list's push target for a NOAA station. Identity travels on the
/// navigation path and the detail view resolves the record: a record on the
/// path is hashed and compared on every render, constituents and all.
enum NoaaRoute: Hashable {
    case tide(StationIndexInfo)
    case current(StationIndexInfo)

    var info: StationIndexInfo {
        switch self {
        case .tide(let s), .current(let s): s
        }
    }
}

/// `station-index.json`, generated by `tools/gen-station-index.mjs`.
struct StationIndex: Decodable {
    let tides: [StationIndexInfo]
    let currents: [StationIndexInfo]

    /// A missing or undecodable index is terminal, exactly as a missing
    /// catalog is: the station list has nothing to render without it.
    static let bundled: StationIndex = {
        guard let url = Bundle.main.url(forResource: "station-index", withExtension: "json"),
              let data = try? Data(contentsOf: url, options: .mappedIfSafe),
              let index = try? JSONDecoder().decode(StationIndex.self, from: data),
              !index.tides.isEmpty, !index.currents.isEmpty
        else {
            let error = CatalogError(resource: "station-index", stage: .decode,
                                     reason: "missing or undecodable station index")
            CatalogDiagnostics.log(error)
            assertionFailure(String(describing: error))
            preconditionFailure(String(describing: error))
        }
        return index
    }()
}
